Implement remaining Beacon namespace endpoints
ralexstokes/beacon-api-client pull request #31
Opened 2022-09-03 18:31 UTC by FancyRatsDave

2022-09-05 14:14 UTC, ralexstokes requested changes
this is excellent! nice work :)

left some comments on a few things to fix/clean up

I also had to go and review the implementation of `Client::post` and how it mapped onto the beacon API specs and that resulted in a refactor here: [20cea63411fc22d5c39fe40d84ee241c1d64e3cd](https://github.com/ralexstokes/beacon-api-client/commit/20cea63411fc22d5c39fe40d84ee241c1d64e3cd)

the issue w/ the usage of `self.http.post` as you did here was that it will ignore any errors from the response which we don't want

if we use `self.post` as of that commit, it should do want we want

so before I can merge this, you'll need to go refactor all of the usages of `self.http.post` to just use `self.post` after you rebase from the `main` branch

2022-09-05 14:14 UTC, ralexstokes commented on src/api_client.rs
> +        let result: Value<BeaconHeaderSummary> = self.get("/eth/v1/beacon/genesis").await?;
```suggestion
        let result: Value<BeaconHeaderSummary> = self.get("/eth/v1/beacon/headers").await?;
```

2022-09-05 14:14 UTC, ralexstokes commented on src/api_client.rs
> +        }
I think we can use the simpler `get` method on `self` here, rather than spelling out all of the details, see e.g. `get_validator`

2022-09-06 18:08 UTC, FancyRatsDave commented
Updated!

2022-09-07 14:05 UTC, ralexstokes requested changes
awesome updates!

one last thing and then we can merge :)

during the refactor to using the latest `post` method, we can simplify as the method already returns the type we want `Result<(), Error>` so we can drop the extra code that does the error checking with the `?` and then skip returning a new `Ok(())`

I left an example suggestion to demonstrate and then marked the other places I saw where we need to update

2022-09-07 14:05 UTC, ralexstokes commented on src/api_client.rs
> +        Ok(())
```suggestion
        self.post("/eth/v1/beacon/blocks", block).await
```

2022-09-07 14:05 UTC, ralexstokes commented on src/api_client.rs
> +        Ok(())
ditto

2022-09-07 14:05 UTC, ralexstokes commented on src/api_client.rs
> +        Ok(())
ditto

2022-09-07 14:05 UTC, ralexstokes commented on src/api_client.rs
> +            .await?;
ditto

2022-09-07 14:05 UTC, ralexstokes commented on src/api_client.rs
> +            .await?;
ditto

2022-09-07 14:05 UTC, ralexstokes commented on src/api_client.rs
> +        self.post("/eth/v1/beacon/pool/sync_committees", messages)
ditto

2022-09-07 14:05 UTC, ralexstokes commented on src/api_client.rs
> +        self.post("/eth/v1/beacon/pool/voluntary_exits", exit)
ditto

2022-09-08 14:10 UTC, FancyRatsDave commented
Updated! Wondering, if we can do this for the `post` functions, cant we also use the same propagation for the simple `get` functions?

```rust
    pub async fn get_beacon_block(&self, id: BlockId) -> Result<SignedBeaconBlock, Error> {
        let result: Value<SignedBeaconBlock> =
            self.get(&format!("eth/v2/beacon/blocks/{id}")).await?;
        Ok(result.data)
    }
```

turns into 

```rust
    pub async fn get_beacon_block(&self, id: BlockId) -> Result<SignedBeaconBlock, Error> {
        self.get(&format!("eth/v2/beacon/blocks/{id}")).await
    }

```

2022-09-09 20:19 UTC, ralexstokes approved these changes
excellent, thanks!

2022-09-09 20:19 UTC, merged